# Site specific settings
title: "Hack_and_Sla.sh"
name: "Hack_and_Sla.sh"
keywords: "Development, Hacking, Security, PowerShell, Python, Programming"
baseurl: "/"
url: "https://devblog.hackandsla.sh"
description: "Much hack. So Slash."
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
twitter: terrabitz
github: terrabitz
keybase: terrabitz

# Build settings
markdown: kramdown
permalink: /:categories/:title/
